#!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:20:00
#SBATCH -J DNA_trimmed_QC
#SBATCH --mail-type=ALL
#SBATCH --mail-user lucas.henriques-faria.9330@student.uu.se
#SBATCH --output=%x.%j.out

# Load modules
module load bioinfo-tools
module load FastQC

# Run FastQC on the specified file
fastqc /home/luhe9330/GA_Data/SRR4342129_1.paired.trimmed.fastq.gz /home/luhe9330/GA_Data/SRR4342129_2.paired.trimmed.fastq.gz -o DNA_trimmed_QC
fastqc /home/luhe9330/GA_Data/SRR4342133_1.paired.trimmed.fastq.gz /home/luhe9330/GA_Data/SRR4342133_2.paired.trimmed.fastq.gz -o DNA_trimmed_QC
fastqc /home/luhe9330/GA_Data/SRR4342137.1.fastq.gz /home/luhe9330/GA_Data/SRR4342137.2.fastq.gz -o RNA_untrimmed_QC
fastqc /home/luhe9330/GA_Data/SRR4342139.1.fastq.gz /home/luhe9330/GA_Data/SRR4342139.2.fastq.gz -o RNA_untrimmed_QC

