#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 16:00:00
#SBATCH -J megahit_assembly
#SBATCH --mail-type=ALL
#SBATCH --mail-user=luhe9330@rackham.uppmax.uu.se

module load bioinfo-tools
module load megahit/1.2.9

R1="/home/luhe9330/GA_Data/SRR4342129_1.paired.trimmed.fastq.gz,/home/luhe9330/GA_Data/SRR4342133_1.paired.trimmed.fastq.gz"
R2="/home/luhe9330/GA_Data/SRR4342129_2.paired.trimmed.fastq.gz,/home/luhe9330/GA_Data/SRR4342133_2.paired.trimmed.fastq.gz"

megahit \
    -1 "$R1" \
    -2 "$R2" \
    --out-dir DNA_Assembly_1 \
    --k-list 79,89,99 \
    --kmin-1pass
