#!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:45:00
#SBATCH -J QUAST_assembly_QC
#SBATCH --mail-type=ALL
#SBATCH --mail-user lucas.henriques-faria.9330@student.uu.se
#SBATCH --output=%x.%j.out

# Load modules
module load bioinfo-tools
module load quast

# Run QUAST
quast.py /domus/h1/luhe9330/GA_Project_Paper3/Scripts/DNA_Assembly_2/final.contigs.fa -o DNA_Assembly_QC_2

