#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 6
#SBATCH -t 06:00:00
#SBATCH -J checkm_binning_quality
#SBATCH --mail-type=ALL
#SBATCH --mail-user=luhe9330@rackham.uppmax.uu.se
#SBATCH --output=%x.%j.out

# Load required modules
module load bioinfo-tools
module load CheckM

# Path to CheckM data directory
export CHECKM_DATA="/domus/h1/luhe9330/GA_Project_Paper3/Scripts/CheckM_data"

# Path to the directory containing MetaBAT2 bins
bins_dir="/domus/h1/luhe9330/GA_Project_Paper3/Scripts/metabat_bins_with_mapping"

# Output directory for CheckM results
output_dir="/domus/h1/luhe9330/GA_Project_Paper3/Scripts/DNA_Binning_QC_4"
mkdir -p "$output_dir"

# Run CheckM to evaluate binning quality
checkm lineage_wf -x fa \
  $bins_dir \
  $output_dir \
  -t 6 -f $output_dir/checkm_summary.txt

echo "CheckM binning quality assessment complete. Results saved in: $output_dir"

